insert into user (username, password, role) values ('slilleycrop0', 'jK4?O(&mS2m}0', 'Construction Expeditor'),
('larmin1', 'iX4#GB>3PoCAi', 'Construction Worker'),
('avittore2', 'rP9}j?BvTbbX"oY"', 'Construction Foreman'),
('braleston3', 'wZ4''Mn(9', 'Surveyor'),
('mgoulston4', 'lZ3{K<x~9`o', 'Engineer'),
('aside5', 'kU2=gy3yQi7T', 'Construction Worker'),
('adearness6', 'dV4~M*f~i<1dsmW', 'Construction Expeditor'),
('hgremain7', 'mF7=k#EJbTAuo''', 'Estimator'),
('ldorrell8', 'sH0@dD1', 'Construction Manager'),
('timpy9', 'sW3%OSzqkN)=m_E', 'Construction Worker'),
('bdeverella', 'iL8@8DhE{Xu', 'Engineer'),
('thesseb', 'nD7<il?{', 'Engineer'),
('tdoncomc', 'gJ7"9CN4)V@`', 'Electrician'),
('mgrennand', 'lU4>U''U`R@/8', 'Estimator'),
('mpadelle', 'kI3<o.X8vZ', 'Electrician'),
('jclacef', 'cG0"aZ''jzcbQT(N', 'Construction Worker'),
('hnanellig', 'sK8@bL#?ANRpu3C', 'Construction Foreman'),
('jmoncreiffeh', 'rA6|rKyjq%J', 'Surveyor'),
('ppidgeoni', 'qQ2~@IIeZ)w~l', 'Construction Manager'),
('bbrokerj', 'yR0<8{U3%5', 'Subcontractor'),
('aabatek', 'wZ8.NJ4a24)Ow', 'Surveyor'),
('mgrisewoodl', 'zK1+t+X4BwQvMHW4', 'Construction Worker'),
('yswateridgem', 'qV1#UaiGi53<~', 'Project Manager'),
('tandersenn', 'pW6_G4kz', 'Supervisor'),
('shinzeo', 'wW4"O=RlAX%x', 'Supervisor'),
('twroughtonp', 'pA7.e<{|1s', 'Construction Expeditor'),
('wmansbridgeq', 'eG5#79JgM1', 'Engineer'),
('jlusgdinr', 'gY2|Xd+yny(70iOb', 'Surveyor'),
('sbaskeyfields', 'jF9}l@.8(JA3W', 'Construction Foreman'),
('alyddont', 'qZ1!''NG+', 'Estimator'),
('ccharterisu', 'nT0_''jybm8', 'Surveyor'),
('ebarnabyv', 'kJ0{`0Re,', 'Architect'),
('gverrierw', 'pL5!*RT4XwLGF', 'Architect'),
('vfleckneyx', 'sB3(8#Rvmxrv=Q', 'Construction Foreman'),
('kgommesy', 'aZ3$|qNhB', 'Construction Worker'),
('cmarksz', 'gB6O$vT06', 'Architect'),
('kkalb10', 'sC2`"NR6(LoD3R(A', 'Construction Manager'),
('pcampsall11', 'tI1{Iip.V%DKy', 'Estimator'),
('mbonnier12', 'eW0#`r>pW_gR', 'Architect'),
('jgendricke13', 'xZ3,1$M''9$o&', 'Engineer'),
('hbrymner14', 'jN9@FSj}X', 'Project Manager'),
('cnunnerley15', 'zV9`e|/(K(5|5SK', 'Supervisor'),
('atoms16', 'aT7$7vTA', 'Estimator'),
('hhammel17', 'aA7(|VkoH{E=zzL', 'Project Manager'),
('btrevain18', 'nA2#}H.5uv"/t|', 'Construction Manager'),
('agrastye19', 'kR6~,7/3', 'Engineer'),
('caberdalgy1a', 'wR7{6ags"EzVm', 'Architect'),
('okezor1b', 'wN5>R`NbH', 'Electrician'),
('teasom1c', 'bL5}Ue<&roGo**V', 'Construction Manager'),
('bklemt1d', 'mW2<5=WHBV', 'Electrician'),
('nchristy1e', 'qD9{MIL">r@<', 'Engineer'),
('drambaut1f', 'cK1%}3)4d6ck', 'Supervisor'),
('bdurker1g', 'sY6mgapd?IJq', 'Estimator'),
('nbryceson1h', 'oW5#w>?"Wr!', 'Subcontractor'),
('ckoppelmann1i', 'wW7(V2lW', 'Construction Manager'),
('rsiuda1j', 'sC7@su}=u', 'Supervisor'),
('ihamerton1k', 'oP4=~>y5r"SywS{', 'Engineer'),
('eschultes1l', 'eB0?NHxvs9`''bH', 'Engineer'),
('jhorsewood1m', 'cN7~kvgx9', 'Construction Expeditor'),
('mheel1n', 'dD7''X1%)?', 'Electrician'),
('nscheffel1o', 'pP1~)K`B~ji`', 'Surveyor'),
('cdivine1p', 'xL9=v`vu/+lX', 'Subcontractor'),
('slipyeat1q', 'oH0*2(A%Re', 'Supervisor'),
('jcristofori1r', 'lA6&Dr66{>P8b9&y', 'Construction Manager'),
('rpresnail1s', 'vY0O4', 'Construction Foreman'),
('tstain1t', 'tA3(q''Vfu', 'Surveyor'),
('fangear1u', 'sX0''7BKTPUB~n', 'Project Manager'),
('hclemmensen1v', 'tU5,&r%rd=+', 'Construction Worker'),
('khotton1w', 'lN5(Ra&rYqP"', 'Subcontractor'),
('skuller1x', 'nI8"1bd/.gT', 'Construction Worker'),
('ctudbald1y', 'sG2=>tUvRC', 'Project Manager'),
('gfoker1z', 'qS7%&<Qwp3Nlb%', 'Supervisor'),
('mfalconbridge20', 'sW6=CTx#?u', 'Engineer'),
('msmalridge21', 'lA8?faeH', 'Construction Foreman'),
('ntombleson22', 'fF6"l+ml7"G?(`<x', 'Construction Expeditor'),
('ljozefczak23', 'mK1%Xo%=@3Wc', 'Engineer'),
('jknutton24', 'eL7<9ftj45,5Gg', 'Construction Foreman'),
('afryett25', 'pI8&CsR{OPZbs', 'Estimator'),
('lstredder26', 'zJ4(czh3PtPtvR/', 'Supervisor'),
('cerdes27', 'gS4*v0B(zp', 'Construction Expeditor'),
('udellatorre28', 'tV4''3yBI>K%fF5e', 'Engineer'),
('nloxly29', 'hX3~{"UGLzT,', 'Subcontractor'),
('cpinkerton2a', 'cF2<''j''Z,y8.y/!', 'Engineer'),
('bhousam2b', 'nU6("?y.iK', 'Electrician'),
('glefevre2c', 'uQ0(d$g}k', 'Construction Manager'),
('sdansie2d', 'fM4.Ho}&+A@B', 'Supervisor'),
('osneezum2e', 'uM7%SfqJbDIx', 'Architect'),
('gkasper2f', 'cH0?x}n2|a*ECym', 'Construction Expeditor'),
('wbardnam2g', 'gO5''tfT$Uu', 'Construction Expeditor'),
('aastill2h', 'iL7*T.m/&=s0kq', 'Surveyor'),
('proarty2i', 'gE5}&AeJ"SLc2', 'Architect'),
('bewbanke2j', 'gN2"NiRW', 'Surveyor'),
('fridings2k', 'zA0,V`PyAX4Zku', 'Supervisor'),
('lvicary2l', 'fK1~EJf.E', 'Subcontractor'),
('schesley2m', 'dT1$ia@b', 'Supervisor'),
('wupston2n', 'bB5{ZF2yySC', 'Engineer'),
('jkellog2o', 'oS8`D@', 'Electrician'),
('rfer2p', 'jG6>X{IG', 'Supervisor'),
('bpanas2q', 'bR2/w_a*7', 'Supervisor'),
('dshelmardine2r', 'dJ4@>FwR9gP&O,i)', 'Surveyor'),
('rloade2s', 'yM7&''"fa', 'Construction Manager'),
('hdykins2t', 'sH6#vN$|eC+o', 'Engineer'),
('hcleghorn2u', 'bO5*alGb0M>!}4#', 'Construction Expeditor'),
('eangric2v', 'eB1$b"/x">ki', 'Construction Worker'),
('rgoodlett2w', 'cN6<>iyR&<UyW', 'Electrician'),
('gzecchi2x', 'lP7$V"q%''O=Qy', 'Subcontractor'),
('lfairfoull2y', 'mP8*%<KWGOf?R', 'Engineer'),
('oaugustus2z', 'uL4=2g99', 'Construction Foreman'),
('bcurtayne30', 'fE9<dwmzx"', 'Surveyor'),
('dleuchars31', 'vD3?''Aq2o{$RS', 'Construction Foreman'),
('mbeeho32', 'qD5}APAKfOZe', 'Project Manager'),
('kteissier33', 'aL9{DfiQc+', 'Estimator'),
('ahartles34', 'qW3`zX', 'Engineer'),
('kbasili35', 'qT7))}S=b=eC4o', 'Estimator'),
('hmack36', 'jO3%%C(L"uL,n6u', 'Construction Manager'),
('ocreenan37', 'eY9/eT', 'Construction Foreman'),
('tcallicott38', 'kR2/>5roe', 'Construction Expeditor'),
('blosseljong39', 'sZ7!PLBUrT8x', 'Construction Expeditor'),
('mfortesquieu3a', 'oU3?B,W%vy_2wL7', 'Supervisor'),
('awavell3b', 'gR0<6cqmB#$P#PW', 'Architect')
